FROM mcr.microsoft.com/dotnet/sdk:8.0 AS development
WORKDIR /app
COPY . .
RUN dotnet restore
EXPOSE 5000
CMD ["dotnet", "watch", "run", "--project", "src/Bio.API/Bio.API.csproj"]

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS production
WORKDIR /app
COPY --from=development /app/src/Bio.API/bin/Release/net8.0/ .
EXPOSE 5000
ENTRYPOINT ["dotnet", "Bio.API.dll"]