"""
API v1 - Model Metrics Endpoint
=================================
GET /api/v1/model-metrics → Evaluation metrics summary (accuracy, F1, per-class).

Public endpoint (no JWT required). Reads from data/evaluation/evaluation_metrics.json
generated by scripts/cnn/05_evaluate_model.py.
"""

import json
import logging
from pathlib import Path
from typing import Any

from fastapi import APIRouter, HTTPException, status

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/v1", tags=["Vision - Model Metrics"])

def _get_metrics_path() -> Path:
    """Dynamically get the evaluation metrics path based on active model version."""
    from app.services.vision.classifier import get_classifier

    classifier = get_classifier()
    if classifier.is_loaded and classifier.active_version and classifier.active_version != "legacy":
        version_dir = Path(__file__).resolve().parent.parent.parent / "data" / "weights" / classifier.active_version
        version_metrics_path = version_dir / "evaluation_metrics.json"
        if version_metrics_path.exists():
            return version_metrics_path

    # Fallback to the root evaluation directory
    return Path(__file__).resolve().parent.parent.parent / "data" / "evaluation" / "evaluation_metrics.json"


# ── Histogram constants ───────────────────────────────────────────────
_F1_BINS = [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.01]
_F1_BIN_LABELS = [
    "0-.1", ".1-.2", ".2-.3", ".3-.4", ".4-.5",
    ".5-.6", ".6-.7", ".7-.8", ".8-.9", ".9-1.0",
]


def _build_f1_histogram(per_class: dict[str, dict]) -> dict[str, Any]:
    """Build a 10-bin histogram of F1 scores across species."""
    f1_values = [m.get("f1_score", 0) for m in per_class.values()]
    counts = [0] * len(_F1_BIN_LABELS)
    for v in f1_values:
        for i in range(len(_F1_BINS) - 1):
            if _F1_BINS[i] <= v < _F1_BINS[i + 1]:
                counts[i] += 1
                break
    return {"labels": _F1_BIN_LABELS, "counts": counts}


def _build_support_distribution(per_class: dict[str, dict]) -> dict[str, int]:
    """Bucket species by their sample-support count."""
    dist: dict[str, int] = {"≤5": 0, "6-10": 0, "11-15": 0, "16+": 0}
    for m in per_class.values():
        s = m.get("support", 0)
        if s <= 5:
            dist["≤5"] += 1
        elif s <= 10:
            dist["6-10"] += 1
        elif s <= 15:
            dist["11-15"] += 1
        else:
            dist["16+"] += 1
    return dist


@router.get(
    "/model-metrics",
    summary="Get model evaluation metrics",
    description=(
        "Returns the evaluation metrics for the CNN model including "
        "accuracy, top-5 accuracy, macro/weighted averages, and "
        "per-class precision, recall, F1-score, and support."
    ),
)
async def model_metrics() -> dict[str, Any]:
    """
    Return evaluation metrics summary for the CNN model.

    Reads dynamically from ``data/weights/{version}/evaluation_metrics.json``
    which is generated during model evaluation (05_evaluate_model.py).

    Response includes:
      - accuracy, top_5_accuracy
      - macro_avg, weighted_avg (precision, recall, f1_score)
      - total_evaluated_species, total_samples
      - f1_histogram: { labels: [...], counts: [...] }
      - support_distribution: { "≤5": N, "6-10": N, "11-15": N, "16+": N }
      - per_class: { species: { precision, recall, f1_score, support } }
    """
    metrics_path = _get_metrics_path()
    if not metrics_path.exists():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Evaluation metrics not found. Run model evaluation first.",
        )

    try:
        with open(metrics_path, encoding="utf-8") as f:
            metrics = json.load(f)
    except Exception as exc:
        logger.error(f"Failed to read evaluation metrics: {exc}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to read evaluation metrics.",
        )

    per_class = metrics.get("per_class", {})

    return {
        "accuracy": metrics.get("accuracy"),
        "top_5_accuracy": metrics.get("top_5_accuracy"),
        "macro_avg": metrics.get("macro_avg"),
        "weighted_avg": metrics.get("weighted_avg"),
        "total_evaluated_species": len(per_class),
        "total_samples": sum(m.get("support", 0) for m in per_class.values()),
        "f1_histogram": _build_f1_histogram(per_class),
        "support_distribution": _build_support_distribution(per_class),
        "per_class": per_class,
    }
