"""
API v1 - Model Metrics Endpoint
=================================
GET /api/v1/model-metrics → Evaluation metrics summary (accuracy, F1, per-class).

Public endpoint (no JWT required). Reads from data/evaluation/evaluation_metrics.json
generated by scripts/cnn/05_evaluate_model.py.
"""

import json
import logging
from pathlib import Path
from typing import Any

from fastapi import APIRouter, HTTPException, status

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/v1", tags=["Vision - Model Metrics"])

# Path to the evaluation metrics file
_EVAL_METRICS_PATH = Path(__file__).resolve().parent.parent.parent / "data" / "evaluation" / "evaluation_metrics.json"


@router.get(
    "/model-metrics",
    summary="Get model evaluation metrics",
    description=(
        "Returns the evaluation metrics for the CNN model including "
        "accuracy, top-5 accuracy, macro/weighted averages, and "
        "per-class precision, recall, F1-score, and support."
    ),
)
async def model_metrics() -> dict[str, Any]:
    """
    Return evaluation metrics summary for the CNN model.

    Reads from ``data/evaluation/evaluation_metrics.json`` which is
    generated during model evaluation (05_evaluate_model.py).
    """
    if not _EVAL_METRICS_PATH.exists():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Evaluation metrics not found. Run model evaluation first.",
        )

    try:
        with open(_EVAL_METRICS_PATH, encoding="utf-8") as f:
            metrics = json.load(f)
    except Exception as exc:
        logger.error(f"Failed to read evaluation metrics: {exc}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to read evaluation metrics.",
        )

    per_class = metrics.get("per_class", {})

    return {
        "accuracy": metrics.get("accuracy"),
        "top_5_accuracy": metrics.get("top_5_accuracy"),
        "macro_avg": metrics.get("macro_avg"),
        "weighted_avg": metrics.get("weighted_avg"),
        "total_evaluated_species": len(per_class),
        "per_class": per_class,
    }
