using Bio.Application.DTOs;
using Bio.Domain.Entities;
using Bio.Domain.Exceptions;
using Bio.Domain.Interfaces;
using MediatR;
using Microsoft.Extensions.Logging;

namespace Bio.Application.Features.Orders.Commands;

public record CreateOrderCommand(OrderCreateDTO Dto, Guid BuyerId) : IRequest<OrderResponseDTO>;

public class CreateOrderCommandHandler : IRequestHandler<CreateOrderCommand, OrderResponseDTO>
{
    private readonly IOrderRepository _orderRepo;
    private readonly IProductRepository _productRepo;
    private readonly ICartRepository _cartRepo;
    private readonly IUnitOfWork _uow;
    private readonly ILogger<CreateOrderCommandHandler> _logger;

    public CreateOrderCommandHandler(
        IOrderRepository orderRepo, IProductRepository productRepo,
        ICartRepository cartRepo, IUnitOfWork uow,
        ILogger<CreateOrderCommandHandler> logger)
    { _orderRepo = orderRepo; _productRepo = productRepo; _cartRepo = cartRepo; _uow = uow; _logger = logger; }

    public async Task<OrderResponseDTO> Handle(CreateOrderCommand request, CancellationToken ct)
    {
        if (request.Dto.Items.Count == 0)
            throw new ValidationException("Order must contain at least one item.");

        // Validate no duplicate product IDs in request
        var duplicates = request.Dto.Items.GroupBy(i => i.ProductId).Where(g => g.Count() > 1).Select(g => g.Key).ToList();
        if (duplicates.Count > 0)
            throw new ValidationException("Duplicate products in order. Combine quantities instead.");

        await _uow.BeginTransactionAsync();
        try
        {
            var orderNumber = await _orderRepo.GenerateOrderNumberAsync(ct);

            // Fetch all products sequentially because DbContext is not thread-safe
            var products = new List<Product?>();
            foreach (var item in request.Dto.Items)
            {
                products.Add(await _productRepo.GetByIdAsync(item.ProductId, ct));
            }

            decimal subtotal = 0;
            var lineItems = new List<(Product Product, int Quantity, decimal UnitPrice)>();

            for (int idx = 0; idx < request.Dto.Items.Count; idx++)
            {
                var item = request.Dto.Items[idx];
                var product = products[idx]
                    ?? throw new NotFoundException(nameof(Product), item.ProductId);

                if (!product.IsActive)
                    throw new ValidationException($"Product '{product.Name}' is not currently available.");

                // DecrementStock validates quantity > 0 and sufficient stock
                product.DecrementStock(item.Quantity);

                var unitPrice = product.SellPrice;
                subtotal += unitPrice * item.Quantity;
                lineItems.Add((product, item.Quantity, unitPrice));
            }

            // Create order
            var order = new Order(
                request.BuyerId, orderNumber, subtotal, subtotal,
                request.Dto.PaymentMethod,
                shippingAddressId: request.Dto.ShippingAddressId,
                billingAddressId: request.Dto.BillingAddressId);

            await _orderRepo.AddAsync(order, ct);
            // We do NOT need to SaveChangesAsync here because order.Id is generated by Guid.NewGuid() in the constructor.
            // Calling it here causes DbUpdateConcurrencyException later when the Cart/Product is modified.

            // Add OrderItems with the actual OrderId (fixes the Guid.Empty bug)
            foreach (var (product, qty, unitPrice) in lineItems)
            {
                var orderItem = new OrderItem(order.Id, product.Id, qty, unitPrice);
                order.OrderItems.Add(orderItem);
            }

            // Clear the purchased active items from the user's cart
            var cart = await _cartRepo.GetByUserIdAsync(request.BuyerId, ct);
            if (cart is not null)
            {
                var orderedProductIds = request.Dto.Items.Select(i => i.ProductId).ToHashSet();
                var itemsToRemove = cart.Items
                    .Where(ci => ci.IsActive && orderedProductIds.Contains(ci.ProductId))
                    .ToList();

                foreach (var cartItem in itemsToRemove)
                    await _cartRepo.RemoveItemAsync(cartItem, ct);

                if (itemsToRemove.Count > 0) cart.Touch();
            }

            await _uow.SaveChangesAsync(ct);
            await _uow.CommitTransactionAsync();

            _logger.LogInformation("Order {OrderNumber} created for buyer {BuyerId}", order.OrderNumber, request.BuyerId);

            var created = await _orderRepo.GetByIdWithItemsAsync(order.Id, ct);
            return MapToResponse(created!);
        }
        catch (Exception ex) when (ex.GetType().Name == "DbUpdateConcurrencyException")
        {
            await _uow.RollbackTransactionAsync();
            _logger.LogWarning(ex, "Concurrency conflict while creating order for buyer {BuyerId}", request.BuyerId);
            throw new ValidationException("One or more products were modified concurrently. Please try again.");
        }
        catch
        {
            await _uow.RollbackTransactionAsync();
            throw;
        }
    }

    internal static OrderResponseDTO MapToResponse(Order o) => new(
        o.Id, o.OrderNumber, o.BuyerId, o.Buyer?.FullName, o.Status,
        o.SubtotalAmount, o.TaxAmount, o.ShippingAmount, o.DiscountAmount, o.TotalAmount,
        o.PaymentMethod, o.TransactionRef,
        o.OrderItems.Select(i => new OrderItemResponseDTO(
            i.Id, i.ProductId, i.Product?.Name ?? "", i.Quantity, i.UnitPrice, i.TotalPrice)).ToList(),
        o.CreatedAt, o.UpdatedAt,
        o.OrderItems.Count,
        MapAddress(o.ShippingAddress),
        MapAddress(o.BillingAddress));

    private static AddressResponseDTO? MapAddress(Address? a) => a is null ? null : new(
        a.Id, a.AddressType, a.RecipientName, a.StreetLine1, a.StreetLine2,
        a.City, a.Department, a.PostalCode, a.Country, a.PhoneNumber, a.IsDefault, a.CreatedAt);
}

public record UpdateOrderStatusCommand(Guid OrderId, string Status) : IRequest<OrderResponseDTO>;

public class UpdateOrderStatusCommandHandler : IRequestHandler<UpdateOrderStatusCommand, OrderResponseDTO>
{
    private readonly IOrderRepository _repo;
    private readonly IUnitOfWork _uow;

    public UpdateOrderStatusCommandHandler(IOrderRepository repo, IUnitOfWork uow)
    { _repo = repo; _uow = uow; }

    public async Task<OrderResponseDTO> Handle(UpdateOrderStatusCommand request, CancellationToken ct)
    {
        var order = await _repo.GetByIdWithItemsAsync(request.OrderId, ct)
            ?? throw new NotFoundException(nameof(Order), request.OrderId);

        // UpdateStatus now enforces the State Machine — throws ValidationException on illegal transition
        order.UpdateStatus(request.Status);
        await _uow.SaveChangesAsync(ct);
        return CreateOrderCommandHandler.MapToResponse(order);
    }
}
